# 32bit only
import json
import win32com.client

iftCertdll = win32com.client.Dispatch("iftCoreEngine.iftGate")
iftServicedll = win32com.client.Dispatch("iftWinExAdapter.clsAdapter")


def cert_nm_pw():
    # return 공인인증서 명칭 비밀번호
    iftCertdll = win32com.client.Dispatch("iftCoreEngine.iftGate")
    req_js_str = ""
    js_str = iftCertdll.getUserCert(req_js_str)
    dic = json.loads(js_str)

    cert_nm = dic["cert_nm"]
    cert_pw = dic["cert_pw"]

    return (str(cert_nm), str(cert_pw))

def map_parm_parmNm():
    pass

map_parm_parmNm = {'appCd': '어플리케이션명',
                'orgCd': '기관코드',
                'svcCd': '서비스코드',
                'loginMethod': '로그인구분',
                'userId': '사용자아이디',
                'userPw': '사용자비밀번호',
                'signCert': '인증서정보',
                'signPri': '개인키정보',
                'signPw': '인증서비밀번호',
                'agentId': '세무대리인관리번호',
                'agentPw': '세무대리인비밀번호',
                'bizNo': '사업자번호',
                'bizEncNo':	'암호화된주민등록번호',
                'bizB64No':	'암호화된주민등록번호',
                'showCookie': '쿠키',
                'txprDscmNo': '사업자번호',
                'txprNm': '거래처명',
                'rprsFnm': '대표자명',
                'sOption': '조회옵션',
                'bizNoArr':	'사업자번호(그룹)',
                'wrtDt': '발행일자',
                'etan':	'승인번호',
                'sumSplCft': '공급가액',
                'splrTxprDscmNo': '공급자자업자번호',
                'dmnrTxprDscmNo': '공급받는자사업자번호',
                'bizNm': '상호',
                'dateGb': '조회일자구분',
                'itemOption': '품목컨테이너조회여부',
                'dtCd':	'조회구분',
                'inqrDtStrt': '조회시작일자',
                'inqrDtEnd': '조회종료일자',
                'inqrYr': '조회년',
                'inqrQt': '조회분기',
                'isnType': '발급유형',
                'bmanCd': '공급받는자선택자',
                'tnmNm': '상호',
                'secCardNo': '보안카드번호',
                'supByr': '매출/매입',
                'taxGb': '세금계산서구분',
                'wrtDtStrt': '조회시작일자',
                'wrtDtEnd': '조회종료일자',
                'wrtYr': '조회년',
                'wrtMnth': '조회월',
                'wrtQt': '조회분기',
                'wrtYrQt': '조회분기멀티조회',
                'ddcYn': '공제구분',
                'trsDt': '조회년',
                'stlYr': '조회년도',
                'qrtFrom': '조회시작분기',
                'qrtTo': '조회종료분기',
                'fromY': '시작연도',
                'toY': '종료연도',
                'fromQ': '시작분기',
                'toQ': '종료분기',
                'cookieData': '세션정보',
                'attrYr': '조회년도',
                'itrfCd': '세목',
                'signB64Pw': '인증서비밀번호',
                'nMemberLoginYn': '비회원로그인여부',
                'telNo': '전화번호',
                'hpNo': '휴대전화번호',
                'email': '이메일',
                'englCvaAplnYn': '발급유형',
                'cvaDcumUseUsgCd': '사용용도',
                'cvaDcumSbmsOrgnClCd': '제출처',
                'resnoOpYn': '주민번호공개여부',
                'adrOpYn': '주소공개여부',
                'cvaDcumGranMthdCd': '수령방법',
                'cerpIsnRqsQty': '발급수량',
                'txnrmStrtYm': '과세기간시작',
                'txnrmEndYm': '과세기간끝',
                'txnrmYm': '과세기간',
                'rtnCvaId': '특정신고조회옵션',
                'dOption': '기준일자조회옵션',
                'detYn': '상세내역조회옵션',
                'detOption': '상세내역조회시옵션',
                'body':	'그룹조회옵션',
                'txprRgtNo': '신고서제출목록_사업자등록번호',
                'dprtUserId': '부서사용자ID',
                'savePath1': '접수증저장경로',
                'savePath2': '납부서저장경로',
                'exePath': 'PDF저장실행파일경로',
                'yyyy': '제출년도',
                'signBEncPw': '인증서비밀번호',
                'mateKndCd': '조회메뉴코드',
                'uOption': '사용자구분옵션'
                }

ift_parm_dic = {'appCd': '',
                'orgCd': '',
                'svcCd': '',
                'loginMethod': '',
                'userId': '',
                'userPw': '',
                'signCert': '',
                'signPri': '',
                'signPw': '',
                'agentId': '',
                'agentPw': '',
                'bizNo': '',
                'bizEncNo':	'',
                'bizB64No':	'',
                'showCookie': '',
                'txprDscmNo': '',
                'txprNm': '',
                'rprsFnm': '',
                'sOption': '',
                'bizNoArr':	'',
                'wrtDt': '',
                'etan':	'',
                'sumSplCft': '',
                'splrTxprDscmNo': '',
                'dmnrTxprDscmNo': '',
                'bizNm': '',
                'dateGb': '',
                'itemOption': '',
                'dtCd':	'',
                'inqrDtStrt': '',
                'inqrDtEnd': '',
                'inqrYr': '',
                'inqrQt': '',
                'isnType': '',
                'bmanCd': '',
                'tnmNm': '',
                'secCardNo': '',
                'supByr': '',
                'taxGb': '',
                'wrtDtStrt': '',
                'wrtDtEnd': '',
                'wrtYr': '',
                'wrtMnth': '',
                'wrtQt': '',
                'wrtYrQt': '',
                'ddcYn': '',
                'trsDt': '',
                'stlYr': '',
                'qrtFrom': '',
                'qrtTo': '',
                'fromY': '',
                'toY': '',
                'fromQ': '',
                'toQ': '',
                'cookieData': '',
                'attrYr': '',
                'itrfCd': '',
                'signB64Pw': '',
                'nMemberLoginYn': '',
                'telNo': '',
                'hpNo': '',
                'email': '',
                'englCvaAplnYn': '',
                'cvaDcumUseUsgCd': '',
                'cvaDcumSbmsOrgnClCd': '',
                'resnoOpYn': '',
                'adrOpYn': '',
                'cvaDcumGranMthdCd': '',
                'cerpIsnRqsQty': '',
                'txnrmStrtYm': '',
                'txnrmEndYm': '',
                'txnrmYm': '',
                'rtnCvaId': '',
                'dOption': '',
                'detYn': '',
                'detOption': '',
                'body':	'',
                'txprRgtNo': '',
                'dprtUserId': '',
                'savePath1': '',
                'savePath2': '',
                'exePath': '',
                'yyyy': '',
                'signBEncPw': '',
                'mateKndCd': '',
                'uOption': ''
                }


def ift_json_obj():
    pass


